# 100 numpy exercises..

1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.20.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3. Create a null vector of size 10 (★☆☆)

In [4]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [6]:
print('%d bytes'%(x.size * x.itemsize))

80 bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
x = np.arange(10,21)
x = x[::-1]
x

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [26]:
x = np.array([1,2,0,0,4,0])
x_ = [x!=0]
x[tuple(x_)]

array([1, 2, 4])

In [27]:
x = np.array([1,2,0,0,4,0]).nonzero()
x

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix (★☆☆)

In [30]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)¶

In [32]:
x = np.random.random((3,3,3))
x

array([[[0.61872304, 0.2386485 , 0.77268477],
        [0.51626778, 0.69307272, 0.72486166],
        [0.07425482, 0.41020853, 0.50139447]],

       [[0.45063305, 0.07719724, 0.44692867],
        [0.41853448, 0.00915819, 0.54039297],
        [0.81259424, 0.27451493, 0.91983852]],

       [[0.21019409, 0.22866937, 0.05606788],
        [0.37058067, 0.74626222, 0.34074329],
        [0.12176728, 0.89657687, 0.16995488]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
x = np.random.random((10,10))
print(x.max(), x.min())

0.9921545090125231 0.0026106843775197675


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
x = np.random.random(30)
x.mean()

0.49711412008834266

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
x = np.ones((10,10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)