# 100 numpy exercises..

In [1]:
import warnings
warnings.filterwarnings('ignore')

**1.Import the numpy package under the name np (★☆☆)**

In [2]:
import numpy as np

**2.Print the numpy version and the configuration (★☆☆)**

In [3]:
print(np.__version__)
np.show_config()

1.20.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


**3.Create a null vector of size 10 (★☆☆)**

In [4]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4.How to find the memory size of any array (★☆☆)**

In [5]:
print('%d bytes'%(x.size * x.itemsize))

80 bytes


**5.How to get the documentation of the numpy add function from the command line? (★☆☆)**

**6.Create a null vector of size 10 but the fifth value which is 1 (★☆☆)**

In [6]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7.Create a vector with values ranging from 10 to 49 (★☆☆)**

In [7]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8.Reverse a vector (first element becomes last) (★☆☆)**

In [8]:
x = np.arange(10,21)
x = x[::-1]
x

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

**9.Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)**

In [9]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10.Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)**

In [10]:
x = np.array([1,2,0,0,4,0])
x_ = [x!=0]
x[tuple(x_)]

array([1, 2, 4])

In [11]:
x = np.array([1,2,0,0,4,0]).nonzero()
x

(array([0, 1, 4]),)

**11.Create a 3x3 identity matrix (★☆☆)**

In [12]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12.Create a 3x3x3 array with random values (★☆☆)**

In [13]:
x = np.random.random((3,3,3))
x

array([[[0.49998636, 0.06465247, 0.52327612],
        [0.98760629, 0.4016628 , 0.08824984],
        [0.92731444, 0.19891375, 0.96495859]],

       [[0.46077769, 0.69155697, 0.37318328],
        [0.11549805, 0.99518816, 0.55190922],
        [0.85148429, 0.47446933, 0.363226  ]],

       [[0.73597583, 0.47117672, 0.42017002],
        [0.50261459, 0.4095195 , 0.59484655],
        [0.41007925, 0.30021352, 0.89308643]]])

**13.Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)**

In [14]:
x = np.random.random((10,10))
print(x.max(), x.min())

0.9895821437831509 0.002094196355122868


**14.Create a random vector of size 30 and find the mean value (★☆☆)**

In [15]:
x = np.random.random(30)
x.mean()

0.538675420999775

**15.Create a 2d array with 1 on the border and 0 inside (★☆☆)**

In [16]:
x = np.ones((10,10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**16.How to add a border (filled with 0's) around an existing array? (★☆☆)**

In [17]:
x = np.zeros((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=1)
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

**17.What is the result of the following expression? (★☆☆)**

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1) # Floating Point Arithmetic: Issues and Limitations

nan
False
False
nan
True
False


**18.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)**

In [19]:
x = np.diag(1+np.arange(4),k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**19.Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)**

In [20]:
x = np.zeros((8,8))
x[::2, ::2] = 1
x[1::2, 1::2] = 1
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**20.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**

In [21]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

**21.Create a checkerboard 8x8 matrix using the tile function (★☆☆)**

In [22]:
x = np.array([[1,0],[0,1]])
np.tile(x,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**22.Normalize a 5x5 random matrix (★☆☆)**

In [23]:
x = np.random.random((5,5))
x = (x - x.mean())/x.std()
x

array([[ 0.27578558, -1.34806521, -0.02169141,  0.96466876,  0.96696905],
       [-0.16911868, -0.7474835 ,  0.42689603, -0.36701103, -1.47955108],
       [-0.91842574, -1.33980088,  1.04523064,  0.64359028, -0.61484213],
       [-1.37091161,  1.67347074, -0.46904548,  1.05537728,  1.80967284],
       [ 1.02387961, -1.40044709,  0.07400527,  0.94313452, -0.65628679]])

**23.Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)**

In [24]:
color = np.dtype([('r', np.ubyte, 1),
                  ('g', np.ubyte, 1),
                  ('b', np.ubyte, 1),
                  ('a', np.ubyte, 1)
                ])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

**24.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)**

In [25]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x,y)
z.shape

(5, 2)

**25.Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)**

In [26]:
x = np.arange(11)
x[(x>3) & (x<9)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

**26.What is the output of the following script? (★☆☆)**

In [27]:
print(sum(range(5),-1)) #10-1

9


**27.Consider an integer vector Z, which of these expressions are legal? (★☆☆)**

In [28]:
Z = np.ones(10)
# Z**Z √
# 2 << Z >> 2
# Z <- Z √
# 1j*Z √
# Z/1/1 √
# Z<Z>Z

**28.What are the result of the following expressions?**

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


**29.How to round away from zero a float array ? (★☆☆)**

**30.How to find common values between two arrays? (★☆☆)**

In [30]:
x = np.arange(0,5)
y = np.arange(3,9)
np.intersect1d(x,y)

array([3, 4])

**31.How to ignore all numpy warnings (not recommended)? (★☆☆)**

In [31]:
import warnings
warnings.filterwarnings('ignore')

**32.Is the following expressions true? (★☆☆)**

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1) # nan 1j

# For negative input elements, a complex value is returned
# (unlike `numpy.sqrt` which returns NaN).

False

**33.How to get the dates of yesterday, today and tomorrow? (★☆☆)**

In [33]:
yest = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomo = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('y -> {}, t -> {}, tomo -> {}'.format(yest, today, tomo))

y -> 2021-11-06, t -> 2021-11-07, tomo -> 2021-11-08


**34.How to get all the dates corresponding to the month of July 2016? (★★☆)**